name: Build and Release Snap

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Snapcraft
        uses: samuelmeuli/action-snapcraft@v1
        with:
          snapcraft-token: ${{ secrets.SNAP_STORE_TOKEN }}

      - name: Build and publish snap
        run: |
          # Build the snap
          snapcraft build

          # Upload to store
          snapcraft upload cursor-installer-gui_*.snap

          # Release to stable channel
          snapcraft release cursor-installer-gui ${{ github.ref_name#v }} stable
