name: Build and Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y dpkg-dev

      - name: Build DEB package
        run: |
          chmod +x create_deb_package.sh
          ./create_deb_package.sh

      - name: Create release files
        run: |
          chmod +x create_release.sh
          ./create_release.sh

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            cursor-installer-v${{ github.ref_name }}.zip
            cursor-installer_1.0.0_all.deb
            cursor_installer_gui.py
            cursor_installer.sh
          body_path: release-v${{ github.ref_name }}/RELEASE_NOTES.md
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
